print('========= DESAFIO 02 =========')
print('Digite a sua data de aniversário.')
dia = input('Dia = ')
mes = input('Mes = ')
ano = input('Ano = ')
print('Você nasceu no dia ', dia, ' de ', mes, ' de ', ano, '. Correto?')
